# yamllint disable rule:line-length
---
- name: Download node_exporter ({{ lazai_arch }})
  ansible.builtin.unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.{{ lazai_os }}-{{ lazai_arch }}.tar.gz"
    dest: "/usr/local/bin/"
    remote_src: true
    extra_opts:
      - "--strip-components=1"
      - "node_exporter-{{ node_exporter_version }}.{{ lazai_os }}-{{ lazai_arch }}/node_exporter"
- name: Create /etc/systemd/system/node_exporter.service
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: "0644"
  vars:
    extra_args: "{{ node_exporter_args }}"
  notify:
    - Start/Enable node_exporter
