services:
  reth0:
    image: ghcr.io/metisprotocol/metis
    container_name: reth0
    volumes:
      - ./rethdata/0:/data/reth/execution-data
      - ./assets:/root/assets/
    ports:
      - "8545:8545"
      - "8551:8551"
      - "9100:9001"
      - "30303:30303"
      - "30303:30303/udp"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    command:
      - "node"
      - "-vvvvv"
      - "--datadir=/data/reth/execution-data"
      - "--chain=/root/assets/genesis.json"
      - "--http"
      - "--http.port=8545"
      - "--http.addr=0.0.0.0"
      - "--http.corsdomain=*"
      - "--http.api=admin,net,eth,web3,debug,txpool,trace"
      - "--authrpc.addr=0.0.0.0"
      - "--authrpc.port=8551"
      - "--authrpc.jwtsecret=/root/assets/jwtsecret"
      - "--metrics=0.0.0.0:9001"
      - "--discovery.port=30303"
      - "--port=30303"
      - "--bootnodes=enode://89e9cf2c4fee0b682a40158e1dd5192a0a87572457ed098ee111638b42090bdc751cb6dd7197659005249b61be8ddc4a59799a4c259ec152cc5835fbbd01a459@reth0:30303"
      - "--txpool.max-account-slots=10000"
      # - "--builder.gaslimit=3600000000" # default * 100
      # - "--builder.interval=10ms"
      # - "--builder.deadline=1" # The deadline in seconds for when the payload builder job should resolve
      # - "--builder.max-tasks=10" # default=3
      # - "--txpool.gas-limit=300000000" # default * 10
      # - "--blobpool.pricebump=1"
      # - "--txpool.pending-max-count=50000" # default=10000
      # - "--txpool.queued-max-count=50000" # default=10000
  reth1:
    image: ghcr.io/metisprotocol/metis
    container_name: reth1
    volumes:
      - ./rethdata/1:/data/reth/execution-data
      - ./assets:/root/assets/
    ports:
      - "18545:8545"
      - "18551:8551"
      - "9101:9001"
      - "40303:30303"
      - "40303:30303/udp"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    command:
      - "node"
      - "-vvvvv"
      - "--datadir=/data/reth/execution-data"
      - "--chain=/root/assets/genesis.json"
      - "--http"
      - "--http.port=8545"
      - "--http.addr=0.0.0.0"
      - "--http.corsdomain=*"
      - "--http.api=admin,net,eth,web3,debug,txpool,trace"
      - "--authrpc.addr=0.0.0.0"
      - "--authrpc.port=8551"
      - "--authrpc.jwtsecret=/root/assets/jwtsecret"
      - "--metrics=0.0.0.0:9001"
      - "--discovery.port=30303"
      - "--port=30303"
      - "--bootnodes=enode://89e9cf2c4fee0b682a40158e1dd5192a0a87572457ed098ee111638b42090bdc751cb6dd7197659005249b61be8ddc4a59799a4c259ec152cc5835fbbd01a459@reth0:30303"
      - "--txpool.max-account-slots=10000"
      # - "--builder.gaslimit=3600000000" # default * 100
      # - "--builder.interval=10ms"
      # - "--builder.deadline=1" # The deadline in seconds for when the payload builder job should resolve
      # - "--builder.max-tasks=10" # default=3
      # - "--txpool.gas-limit=300000000" # default * 10
      # - "--blobpool.pricebump=1"
      # - "--txpool.pending-max-count=50000" # default=10000
      # - "--txpool.queued-max-count=50000" # default=10000
  reth2:
    image: ghcr.io/metisprotocol/metis
    container_name: reth2
    volumes:
      - ./rethdata/2:/data/reth/execution-data
      - ./assets:/root/assets/
    ports:
      - "28545:8545"
      - "28551:8551"
      - "9102:9001"
      - "50303:30303"
      - "50303:30303/udp"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    command:
      - "node"
      - "-vvvvv"
      - "--datadir=/data/reth/execution-data"
      - "--chain=/root/assets/genesis.json"
      - "--http"
      - "--http.port=8545"
      - "--http.addr=0.0.0.0"
      - "--http.corsdomain=*"
      - "--http.api=admin,net,eth,web3,debug,txpool,trace"
      - "--authrpc.addr=0.0.0.0"
      - "--authrpc.port=8551"
      - "--authrpc.jwtsecret=/root/assets/jwtsecret"
      - "--metrics=0.0.0.0:9001"
      - "--discovery.port=30303"
      - "--port=30303"
      - "--bootnodes=enode://89e9cf2c4fee0b682a40158e1dd5192a0a87572457ed098ee111638b42090bdc751cb6dd7197659005249b61be8ddc4a59799a4c259ec152cc5835fbbd01a459@reth0:30303"
      - "--txpool.max-account-slots=10000"
      # - "--builder.gaslimit=3600000000" # default * 100
      # - "--builder.interval=10ms"
      # - "--builder.deadline=1" # The deadline in seconds for when the payload builder job should resolve
      # - "--builder.max-tasks=10" # default=3
      # - "--txpool.gas-limit=300000000" # default * 10
      # - "--blobpool.pricebump=1"
      # - "--txpool.pending-max-count=50000" # default=10000
      # - "--txpool.queued-max-count=50000" # default=10000
