---
# lazai_env: mainnet # [required]
lazai_role: rpc # one of "seq", "rpc"
lazai_apt_mode: 'deb822_repository' # 'apt_repository', 'deb822_repository'
lazai_sysctl_enabled: true
lazai_sysctl:
  net.core.rmem_default: "134217728"
  net.core.rmem_max: "134217728"
  net.core.wmem_default: "134217728"
  net.core.wmem_max: "134217728"
  vm.max_map_count: "2024000000"
  fs.nr_open: "2147483584" # 33554432
  fs.aio-max-nr: "8388608" # 1048576
  net.core.somaxconn: "524288"
  net.ipv4.ip_local_port_range: "1024 65535"
  net.ipv4.tcp_tw_reuse: "2" # For TCP TIME-WAIT reuse. Set to 1 if unsure; 2 is aggressive and kernel >= 5.4 only.
  net.ipv4.tcp_timestamps: "1"
  net.ipv4.tcp_max_syn_backlog: "524288"
  net.core.netdev_max_backlog: "524288"
lazai_ufw_enabled: true
lazai_node_exporter_enabled: true
lazai_node_exporter_version: 1.9.1
lazai_node_exporter_args: --web.listen-address 127.0.0.1:9100 --collector.systemd
lazai_lazai_enabled: true
lazai_blockscout_enabled: false
lazai_mala_image: ghcr.io/0xlazai/malachitebft:v0.7.2
lazai_reth_image: ghcr.io/0xlazai/lazchain:v0.7.2
lazai_blockscout_frontend_image: ghcr.io/0xlazai/frontend:v2.4.1-1c38a14
lazai_blockscout_backend_image: ghcr.io/blockscout/blockscout:8.1.2
lazai_bin: /usr/sbin/nologin
lazai_user: lazai
lazai_group: lazai
lazai_home: /opt/nodes
lazai_lazai_dirs:
  - "{{ lazai_home }}"
  - "{{ lazai_home }}/{{ lazai_node_name }}"
  - "{{ lazai_home }}/{{ lazai_node_name }}/mala"
  - "{{ lazai_home }}/{{ lazai_node_name }}/mala/data"
  - "{{ lazai_home }}/{{ lazai_node_name }}/mala/data/config"
  - "{{ lazai_home }}/{{ lazai_node_name }}/reth"
  - "{{ lazai_home }}/{{ lazai_node_name }}/reth/rethdata"
  - "{{ lazai_home }}/{{ lazai_node_name }}/assets"
  - "{{ lazai_home }}/{{ lazai_node_name }}/logs"
lazai_blockscout_dirs:
  - "{{ lazai_home }}"
  - "{{ lazai_home }}/{{ lazai_node_name }}"
  - "{{ lazai_home }}/{{ lazai_node_name }}/blockscout"
  - "{{ lazai_home }}/{{ lazai_node_name }}/blockscout/env"
lazai_sequencers:
  - name: "pub.rpc0.mainnet.lazai.systems"
    id: "b733787be3ef75eb2dc6a21f218f1285bb5210d541b64839d2de9b547bae2fe07541a47e678aa6a2c8234437a18a5da07a0181f96fa241a6d943b5e4b40f9244"
    addr: "3.151.46.215"
    port: "30303"
  - name: "pub.rpc1.mainnet.lazai.systems"
    id: "da91c3a9530ac839e90255801638ffa33c4e84f116cea2e9283178ef283a1d0f1fe88ccf365ad95dbc5cad0095c640647fa4a2e3d1139cf8b5a1605c1e0ac6c1"
    addr: "3.0.225.122"
    port: "30303"
